# Generated by Django 5.0.6 on 2024-09-15 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_about_profile_project_skill_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomePageProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('project_image', models.ImageField(upload_to='homepage_projects/')),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_projects', to='myapp.homepage')),
            ],
        ),
    ]
