# Generated by Django 5.0.6 on 2024-09-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_homepage_homepageproject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='content',
            new_name='description',
        ),
    ]
